SELECT  * FROM STUDENT;

INSERT INTO STUDENT values(10, 'kim', 70, 90);
INSERT INTO STUDENT values(11, 'kim1', 70, 90);
INSERT INTO STUDENT values(12, 'kim2', 80, 90);
INSERT INTO STUDENT values(13, 'kim3', 70, 100);

COMMIT;

#데이터 삭제 : DELETE
#DELETE FROM 테이블명 WHERE 조건;
DELETE FROM STUDENT;

DELETE FROM STUDENT WHERE KOR_SCORE >= 80;

#데이터 수정 : UPDATE
UPDATE STUDENT 
SET 
STU_NAME = 'aaa',
KOR_SCORE = 100
