DROP TABLE IF EXISTS BASIC_BOARD;

CREATE TABLE BASIC_BOARD(
    BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(30),
    WRITER VARCHAR(20),
    CONTENT VARCHAR(50),
    READ_CNT INT DEFAULT 0,
    CREATE_DATE DATETIME DEFAULT SYSDATE()
);

-- 번호는 절대 넣지 말 것!
INSERT INTO BASIC_BOARD (TITLE, WRITER, CONTENT)
VALUES ('첫 번째 글', '김자바', '첫번째 내용');

INSERT INTO BASIC_BOARD (TITLE, WRITER, CONTENT)
VALUES ('두 번째 글', '김자바', '두번째 내용');

INSERT INTO BASIC_BOARD (TITLE, WRITER, CONTENT)
VALUES ('세 번째 글', '김자바', '세번째 내용');

SELECT * FROM BASIC_BOARD;
